name: Node.js CI for SDK

on:
  push:
    branches: [ master ]
    paths:
      - "kimi/**"
  pull_request:
    branches: [ master ]
    paths:
      - "kimi/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: kimi/package-lock.json
    - run: npm i
      working-directory: ./kimi
    - run: npm run lint
      working-directory: ./kimi
    - run: npm run test-cov
      working-directory: ./kimi
      env:
        KIMI_API_KEY: ${{ secrets.API_KEY }}
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required
        directory: ./kimi
